CREATE TABLE IF NOT EXISTS submit_app
(
    application_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applied_at     TIMESTAMP,
    job_id         BIGINT NOT NULL,
    updated_at     TIMESTAMP,
    applicant_id   VARCHAR(255) NOT NULL,
    cover_letter   TEXT,
    resume_url     VARCHAR(255) NOT NULL,
    status         VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_submit_app_job_id
    ON submit_app(job_id);