CREATE TABLE company
(
    company_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    description   TEXT         NOT NULL,
    website       VARCHAR(255) NOT NULL,
    user_id       VARCHAR(255) NOT NULL,
    email         VARCHAR(255),
    location      VARCHAR(255) NOT NULL,
    rating        DOUBLE PRECISION,
    created_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
