CREATE TABLE IF NOT EXISTS job
(
    job_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    BIGINT    NOT NULL,
    contract_type VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP,
    description   TEXT NOT NULL,
    last_modified TIMESTAMP,
    location     VARCHAR(255) NOT NULL,
    max_salary    VARCHAR(255) NOT NULL,
    min_salary    VARCHAR(255) NOT NULL,
    title         VARCHAR(255) NOT NULL
);